name: Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11.1"

      - name: Créer debug keystore Android
        run: |
          mkdir -p ~/.config/.android

          keytool -genkeypair \
            -v \
            -keystore ~/.config/.android/debug.keystore \
            -storepass android \
            -alias AndroidDebugKey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

      - name: Générer le rapport de signature SHA Firebase
        run: |
          chmod +x gradlew
          ./gradlew signingReport

      - name: Compiler l'APK debug
        run: gradle assembleDebug

      - name: Publier l'APK
        uses: actions/upload-artifact@v4
        with:
          name: pdf-by-kanto-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
